# -*- coding: utf-8 -*-
"""NLP_by_NN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z5DGvLFSWbXNwl71_a4d3VIh6wa0D7pn
"""

import re
import string
import copy

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

import pandas as pd

url = "https://huggingface.co/datasets/SetFit/amazon_reviews_multi_en/resolve/main/train.jsonl"

df = pd.read_json(url, lines=True)



df = df[["text", "label"]]

def label_to_sentiment(label):
    if label <= 1:
        return "Negative"
    elif label == 2:
        return "Neutral"
    else:
        return "Positive"

df["sentiment"] = df["label"].apply(label_to_sentiment)

df.rename(columns={"text": "review", "label": "original_label"}, inplace=True)

encoder = LabelEncoder()

df["label"] = encoder.fit_transform(df["sentiment"])

df = df[["review", "sentiment", "label"]]

print(encoder.classes_)

df.head()

df.info()

df.describe()

modes = df.mode().iloc[0]
modes

cat_cols = df.select_dtypes(include='object').columns
missing_count = (df[cat_cols] == ' ?').sum()
missing_count

df['sentiment'].value_counts()

df['review'].value_counts().head(10)

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8,5))

sns.countplot(
    x="sentiment",
    data=df,
    order=df["sentiment"].value_counts().index
)

plt.title("Sentiment Distribution")
plt.xlabel("Sentiment")
plt.ylabel("Number of Reviews")

plt.show()

df["sentiment"].value_counts().plot(
    kind="pie",
    autopct="%1.1f%%",
    figsize=(6,6)
)

plt.title("Sentiment Percentage Distribution")
plt.ylabel("")
plt.show()

sample_size = 30000
random_state = 42

df_model = df.sample(sample_size, random_state=random_state).reset_index(drop=True)

import re
import string
import nltk

nltk.download('stopwords')
from nltk.corpus import stopwords

def basic_clean_text(text):
    # 1. lowercase
    text = text.lower()

    # 2. remove urls
    text = re.sub(r"http\S+|www\S+", "", text)

    # 3. remove punctuation
    text = re.sub(f"[{re.escape(string.punctuation)}]", " ", text)

    # 4. remove numbers
    text = re.sub(r"\d+", "", text)

    # 5. remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text

df_model["clean_review"] = df_model["review"].apply(basic_clean_text)

df_model[["review", "clean_review"]].head()

random_state = 42

X_train_text, X_temp_text, y_train, y_temp = train_test_split(
    df_model["clean_review"],
    df_model["label"],
    test_size=0.30,
    random_state=random_state,
    stratify=df_model["label"]
)

X_val_text, X_test_text, y_val, y_test = train_test_split(
    X_temp_text,
    y_temp,
    test_size=0.50,
    random_state=random_state,
    stratify=y_temp
)

print(X_train_text.shape)
print(X_val_text.shape)
print(X_test_text.shape)

def tokenize(text):
    return str(text).lower().split()

vocab = set()

for review in X_train_text:
    words = tokenize(review)
    vocab.update(words)

word_to_ix = {
    "<PAD>": 0,
    "<UNK>": 1
}

for word in vocab:
    word_to_ix[word] = len(word_to_ix)

ix_to_word = {ix: word for word, ix in word_to_ix.items()}

vocab_size = len(word_to_ix)

print("vocab size:", vocab_size)

max_len = 30

def review_to_indices(review):
    words = tokenize(review)

    indices = []

    for word in words:
        if word in word_to_ix:
            indices.append(word_to_ix[word])
        else:
            indices.append(word_to_ix["<UNK>"])

    if len(indices) < max_len:
        indices = indices + [word_to_ix["<PAD>"]] * (max_len - len(indices))
    else:
        indices = indices[:max_len]

    return indices

X_train_seq = np.array([review_to_indices(review) for review in X_train_text])
X_val_seq = np.array([review_to_indices(review) for review in X_val_text])
X_test_seq = np.array([review_to_indices(review) for review in X_test_text])

print(X_train_seq.shape)
print(X_val_seq.shape)
print(X_test_seq.shape)

class HybridEmbeddingMLP(nn.Module):
    def __init__(
        self,
        vocab_size,
        embedding_dim,
        max_len,
        feature_size,
        hidden1,
        hidden2,
        num_classes,
        dropout_rate
    ):
        super().__init__()

        self.embedding = nn.Embedding(
            num_embeddings=vocab_size,
            embedding_dim=embedding_dim,
            padding_idx=0
        )

        embedding_size = max_len * embedding_dim

        input_size = embedding_size

        self.classifier = nn.Sequential(
            nn.Linear(input_size, hidden1),
            nn.BatchNorm1d(hidden1),
            nn.ReLU(),
            nn.Dropout(dropout_rate),

            nn.Linear(hidden1, hidden2),
            nn.BatchNorm1d(hidden2),
            nn.ReLU(),
            nn.Dropout(dropout_rate),

            nn.Linear(hidden2, num_classes)
        )

    def forward(self, x_seq, x_features):
        embedded = self.embedding(x_seq)


        combined = torch.cat((embedded, x_features), dim=1)

        output = self.classifier(combined)

        return output

def train_model(
    X_train_seq,
    X_train_features,
    y_train,
    X_val_seq,
    X_val_features,
    y_val,
    feature_size,
    experiment_name,
    epochs=20,
    batch_size=64,
    lr=0.001,
    weight_decay=1e-4,
    patience=5
):
    embedding_dim = 50
    hidden1 = 256
    hidden2 = 128
    num_classes = 3
    dropout_rate = 0.3

    X_train_seq_tensor = torch.LongTensor(X_train_seq)
    X_val_seq_tensor = torch.LongTensor(X_val_seq)

    X_train_features_tensor = torch.FloatTensor(X_train_features)
    X_val_features_tensor = torch.FloatTensor(X_val_features)

    y_train_tensor = torch.LongTensor(np.array(y_train).astype("int64"))
    y_val_tensor = torch.LongTensor(np.array(y_val).astype("int64"))

    train_dataset = TensorDataset(
        X_train_seq_tensor,
        X_train_features_tensor,
        y_train_tensor
    )

    val_dataset = TensorDataset(
        X_val_seq_tensor,
        X_val_features_tensor,
        y_val_tensor
    )

    train_loader = DataLoader(
        train_dataset,
        batch_size=batch_size,
        shuffle=True
    )

    val_loader = DataLoader(
        val_dataset,
        batch_size=batch_size,
        shuffle=False
    )

    model = HybridEmbeddingMLP(
        vocab_size=vocab_size,
        embedding_dim=embedding_dim,
        max_len=max_len,
        feature_size=feature_size,
        hidden1=hidden1,
        hidden2=hidden2,
        num_classes=num_classes,
        dropout_rate=dropout_rate
    ).to(device)

    criterion = nn.CrossEntropyLoss()

    optimizer = optim.Adam(
        model.parameters(),
        lr=lr,
        weight_decay=weight_decay
    )

    scheduler = optim.lr_scheduler.StepLR(
        optimizer,
        step_size=5,
        gamma=0.5
    )

    train_losses = []
    val_losses = []
    train_accs = []
    val_accs = []

    best_val_loss = float("inf")
    best_model_state = None
    patience_counter = 0

    for epoch in range(epochs):
        model.train()

        total_train_loss = 0
        correct_train = 0
        total_train = 0

        for batch_seq, batch_features, batch_y in train_loader:
            batch_seq = batch_seq.to(device)
            batch_features = batch_features.to(device)
            batch_y = batch_y.to(device)

            optimizer.zero_grad()

            outputs = model(batch_seq, batch_features)

            loss = criterion(outputs, batch_y)

            loss.backward()

            optimizer.step()

            total_train_loss += loss.item() * batch_y.size(0)

            preds = torch.argmax(outputs, dim=1)

            total_train += batch_y.size(0)

        avg_train_loss = total_train_loss / total_train

        train_acc = correct_train / total_train

        model.eval()

        total_val_loss = 0
        correct_val = 0
        total_val = 0

        with torch.no_grad():
            for batch_seq, batch_features, batch_y in val_loader:
                batch_seq = batch_seq.to(device)
                batch_features = batch_features.to(device)
                batch_y = batch_y.to(device)

                outputs = model(batch_seq, batch_features)

                loss = criterion(outputs, batch_y)

                total_val_loss += loss.item() * batch_y.size(0)

                preds = torch.argmax(outputs, dim=1)

                total_val += batch_y.size(0)

        avg_val_loss = total_val_loss / total_val

        val_acc = correct_val / total_val

        scheduler.step()

        train_losses.append(avg_train_loss)
        val_losses.append(avg_val_loss)
        train_accs.append(train_acc)
        val_accs.append(val_acc)

        print(
            f"{experiment_name} | "
            f"Epoch {epoch + 1}/{epochs} | "
            f"Train Loss: {avg_train_loss:.4f} | "
            f"Val Loss: {avg_val_loss:.4f} | "
            f"Train Acc: {train_acc:.4f} | "
            f"Val Acc: {val_acc:.4f}"
        )

        if avg_val_loss < best_val_loss:
            best_val_loss = avg_val_loss
            best_model_state = copy.deepcopy(model.state_dict())
            patience_counter = 0
        else:
            patience_counter += 1

        if patience_counter >= patience:
            print("Early stopping triggered.")
            break

    model.load_state_dict(best_model_state)

    history = {
        "train_loss": train_losses,
        "val_loss": val_losses,
        "train_acc": train_accs,
        "val_acc": val_accs
    }

    return model, history

def evaluate_model(
    model,
    X_test_seq,
    X_test_features,
    y_test,
    experiment_name,
    batch_size=64
):
    X_test_seq_tensor = torch.LongTensor(X_test_seq)

    X_test_features_tensor = torch.FloatTensor(X_test_features)

    y_test_tensor = torch.LongTensor(np.array(y_test).astype("int64"))

    test_dataset = TensorDataset(
        X_test_seq_tensor,
        X_test_features_tensor,
        y_test_tensor
    )

    test_loader = DataLoader(
        test_dataset,
        batch_size=batch_size,
        shuffle=False
    )

    model.eval()

    all_preds = []
    all_labels = []

    with torch.no_grad():
        for batch_seq, batch_features, batch_y in test_loader:
            batch_seq = batch_seq.to(device)
            batch_features = batch_features.to(device)

            outputs = model(batch_seq, batch_features)

            preds = torch.argmax(outputs, dim=1)

            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(batch_y.numpy())

    acc = accuracy_score(all_labels, all_preds)

    print(experiment_name)

    print("Test Accuracy:", acc)

    print(
        classification_report(
            all_labels,
            all_preds,
            target_names=list(encoder.classes_),
            zero_division=0
        )
    )

    print("Confusion Matrix:")
    print(confusion_matrix(all_labels, all_preds))

    return acc

def plot_history(history, title):
    plt.figure(figsize=(8, 5))

    plt.plot(history["train_loss"], label="Train Loss")
    plt.plot(history["val_loss"], label="Validation Loss")

    plt.title(title + " - Loss")
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.legend()

    plt.show()

    plt.figure(figsize=(8, 5))

    plt.plot(history["train_acc"], label="Train Accuracy")
    plt.plot(history["val_acc"], label="Validation Accuracy")

    plt.title(title + " - Accuracy")
    plt.xlabel("Epoch")
    plt.ylabel("Accuracy")
    plt.legend()

    plt.show()

max_features = 3000

bow_vectorizer = CountVectorizer(
    max_features=max_features,
    min_df=3,
    max_df=0.9
)

X_train_bow = bow_vectorizer.fit_transform(X_train_text)
X_val_bow = bow_vectorizer.transform(X_val_text)
X_test_bow = bow_vectorizer.transform(X_test_text)

X_train_bow = X_train_bow.toarray().astype("float32")
X_val_bow = X_val_bow.toarray().astype("float32")
X_test_bow = X_test_bow.toarray().astype("float32")

print(X_train_bow.shape)
print(X_val_bow.shape)
print(X_test_bow.shape)



model_exp1, history_exp1 = train_model(
    X_train_seq=X_train_seq,
    X_train_features=X_train_bow,
    y_train=y_train,
    X_val_seq=X_val_seq,
    X_val_features=X_val_bow,
    y_val=y_val,
    feature_size=X_train_bow.shape[1],
    experiment_name="Experiment 1: Embedding + BoW + MLP"
)

acc_exp1 = evaluate_model(
    model=model_exp1,
    X_test_seq=X_test_seq,
    X_test_features=X_test_bow,
    y_test=y_test,
    experiment_name="Experiment 1: Embedding + BoW + MLP"
)

plot_history(
    history=history_exp1,
    title="Experiment 1: Embedding + BoW + MLP"
)

max_features = 3000

tfidf_vectorizer = TfidfVectorizer(
    max_features=max_features,
    min_df=3,
    max_df=0.9,
    ngram_range=(1, 1)
)

X_train_tfidf = tfidf_vectorizer.fit_transform(X_train_text)
X_val_tfidf = tfidf_vectorizer.transform(X_val_text)
X_test_tfidf = tfidf_vectorizer.transform(X_test_text)

X_train_tfidf = X_train_tfidf.toarray().astype("float32")
X_val_tfidf = X_val_tfidf.toarray().astype("float32")
X_test_tfidf = X_test_tfidf.toarray().astype("float32")

print(X_train_tfidf.shape)
print(X_val_tfidf.shape)
print(X_test_tfidf.shape)

model_exp2, history_exp2 = train_model(
    X_train_seq=X_train_seq,
    X_train_features=X_train_tfidf,
    y_train=y_train,
    X_val_seq=X_val_seq,
    X_val_features=X_val_tfidf,
    y_val=y_val,
    feature_size=X_train_tfidf.shape[1],
    experiment_name="Experiment 2: Embedding + TF-IDF + MLP"
)

acc_exp2 = evaluate_model(
    model=model_exp2,
    X_test_seq=X_test_seq,
    X_test_features=X_test_tfidf,
    y_test=y_test,
    experiment_name="Experiment 2: Embedding + TF-IDF + MLP"
)

plot_history(
    history=history_exp2,
    title="Experiment 2: Embedding + TF-IDF + MLP"
)

def handle_negation(text):
    words = str(text).split()

    new_words = []

    i = 0

    while i < len(words):
        if words[i] in {"not", "no", "never"} and i + 1 < len(words):
            new_words.append(words[i] + "_" + words[i + 1])
            i += 2
        else:
            new_words.append(words[i])
            i += 1

    return " ".join(new_words)
    #words = ["this", "movie", "is", "not", "good"]
    #new_words = ["this", "movie", "is", "not_good"]

X_train_advanced = X_train_text.apply(handle_negation)
X_val_advanced = X_val_text.apply(handle_negation)
X_test_advanced = X_test_text.apply(handle_negation)

positive_words = {
    "good", "great", "excellent", "amazing", "perfect",
    "love", "best", "nice", "awesome", "fantastic"
}

negative_words = {
    "bad", "worst", "terrible", "broken", "poor",
    "hate", "awful", "disappointed", "defective", "waste"
}

def extract_extra_features(text):
    text = str(text).lower()

    words = text.split()

    positive_count = sum(1 for word in words if word in positive_words)

    negative_count = sum(1 for word in words if word in negative_words)

    exclamation_count = text.count("!")

    question_count = text.count("?")

    review_length = len(words)

    return [
        positive_count,
        negative_count,
        exclamation_count,
        question_count,
        review_length
    ]

train_extra = np.array([extract_extra_features(text) for text in X_train_text])
val_extra = np.array([extract_extra_features(text) for text in X_val_text])
test_extra = np.array([extract_extra_features(text) for text in X_test_text])

scaler = StandardScaler()

train_extra_scaled = scaler.fit_transform(train_extra).astype("float32")
val_extra_scaled = scaler.transform(val_extra).astype("float32")
test_extra_scaled = scaler.transform(test_extra).astype("float32")

max_features = 3000

tfidf_ngram_vectorizer = TfidfVectorizer(
    max_features=max_features,
    min_df=3,
    max_df=0.9,
    ngram_range=(1, 2)
)

X_train_tfidf_ngram = tfidf_ngram_vectorizer.fit_transform(X_train_advanced)
X_val_tfidf_ngram = tfidf_ngram_vectorizer.transform(X_val_advanced)
X_test_tfidf_ngram = tfidf_ngram_vectorizer.transform(X_test_advanced)

X_train_tfidf_ngram = X_train_tfidf_ngram.toarray().astype("float32")
X_val_tfidf_ngram = X_val_tfidf_ngram.toarray().astype("float32")
X_test_tfidf_ngram = X_test_tfidf_ngram.toarray().astype("float32")

model_exp3, history_exp3 = train_model(
    X_train_seq=X_train_seq,
    X_train_features=X_train_exp3_features,
    y_train=y_train,
    X_val_seq=X_val_seq,
    X_val_features=X_val_exp3_features,
    y_val=y_val,
    feature_size=X_train_exp3_features.shape[1],
    experiment_name="Experiment 3: Embedding + Improved TF-IDF + Extra Features + MLP"
)

acc_exp3 = evaluate_model(
    model=model_exp3,
    X_test_seq=X_test_seq,
    X_test_features=X_test_exp3_features,
    y_test=y_test,
    experiment_name="Experiment 3: Embedding + Improved TF-IDF + Extra Features + MLP"
)

plot_history(
    history=history_exp3,
    title="Experiment 3: Embedding + Improved TF-IDF + Extra Features + MLP"
)

from google.colab import files

files.download("ex3_sentiment_model.pth")
files.download("word_to_ix.pkl")
files.download("encoder.pkl")
files.download("tfidf_ngram_vectorizer.pkl")
files.download("extra_scaler.pkl")
files.download("ex3_config.pkl")





